# Generated by Django 4.0.3 on 2022-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameM', models.TextField(blank=True, null=True)),
                ('emailM', models.TextField(blank=True, null=True)),
                ('endM', models.TextField(blank=True, null=True)),
                ('cityM', models.TextField(blank=True, null=True)),
                ('ufM', models.TextField(blank=True, null=True)),
                ('nameInstM', models.TextField(blank=True, null=True)),
                ('dateInstM', models.TextField(blank=True, null=True)),
                ('membersQt', models.IntegerField(blank=True, null=True)),
                ('infoInstM', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
